- name: 
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Task output
    register: result
    ospf_element:
      smc_logging:
        level: 10
        path: ansible-smc.log
      elements:
      - ospfv2_interface_settings:
          authentication_type: none
          dead_interval: 40
          hello_interval: 10
          hello_interval_type: normal
          mtu_mismatch_detection: true
          name: myinterface
          password: ''
          retransmit_interval: 5
          router_priority: 1
          transmit_delay: 1
