- name: create or delete interfaces
  hosts: localhost
  gather_facts: no
  tasks:
  - name: add a layer 3 interface to a single fw
    register: result
    # Create a cluster interface
    l3fw_cluster_interface:
      name: mycluster
      cluster_vip: 3.3.3.1
      cluster_vip_mask: 3.3.3.0/24
      cluster_macaddress: 02:02:02:02:02:04
      cluster_nic_id: 3
      cluster_nodes:
        - address: 3.3.3.2
          network_value: 3.3.3.0/24
          nodeid: 1
        - address: 3.3.3.3
          network_value: 3.3.3.0/24
          nodeid: 2
  - name: dump test output
    debug:
      msg: '{{ result }}'