- name: creating and deleting layer 3 firewalls
  hosts: localhost
  gather_facts: no
  tasks:
  - name: create a single layer 3 firewall
    register: result
    vpn_site:
      
    policy_vpn:
      name: myvpn
      central:
        - engine1
        - engine2
      satellite:
        - engine3
        - engine4
      profile: VPN-Suite-A

  - name: dump test output
    debug:
      msg: '{{ result }}'