- name: create or delete interfaces
  hosts: localhost
  gather_facts: no
  tasks:
  - name: add a layer 3 interface to a single fw
    network_element_facts:
      limit: 2
      filter: network-4.4.4.0/24
      exact_match: no