- name: Firewall Actions
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Generate initial config
    register: command_output
    engine_action:
      smc_logging:
        level: 10
        path: ansible-smc.log
      name: myfw3
      nodeid: 1
      action: initial_contact
      extra_args:
        enable_ssh: true
        as_base64: true

  - debug: msg="{{ command_output.msg }}"

  - name: Reboot node
    engine_action:
      name: myfw3
      nodeid: 1
      action: go_online
      extra_args:
        comment: bringing back online