- name: Facts related to external VPN gateways
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Retrieve all external GW's
    external_gateway_facts:
  
  - name: Get a specific external GW details
    external_gateway_facts:
      filter: myremotevpn
  
  - name: Get a specific external GW, and expand supported attributes
    external_gateway_facts:
      filter: extgw3
      expand:
        - gateway_profile
        - vpn_site
      