- name: Create an external gateway playbook
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create an external gateway
    external_gateway:
      name: dynamicendpoint
      endpoint:
        - name: mydynamicendpoint
          dynamic: yes
          ike_phase1_id_type: 1
          ike_phasee1_id_value: a@a.com
      tags: footag
