- name: create or delete interfaces
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create an external gateway
    vpn_external_gw:
      name: newextgw
      endpoint_ip: 1.1.1.1
      networks:
        - 3.3.3.0/24
        - 4.4.4.0/24
      nat_t: yes
      mode: active
      tags: 
        - footag
      