- name: creating and deleting layer 3 firewalls
  connection: local
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create a layer 3 FW cluster with 3 members
    l3fw_cluster:
      name: mycluster
      cluster_vip: 1.1.1.1
      cluster_vip_mask: 1.1.1.0/24
      cluster_macaddress: 02:02:02:02:02:02
      cluster_nic_id: 0
      cluster_mode: standby
      cluster_nodes:
        - address: 1.1.1.2
          network_value: 1.1.1.0/24
          nodeid: 1
        - address: 1.1.1.3
          network_value: 1.1.1.0/24
          nodeid: 2
        - address: 1.1.1.4
          network_value: 1.1.1.0/24
          nodeid: 3
      default_nat: yes
      domain_server_address:
          - 10.0.0.1
          - 10.0.0.2
      enable_antivirus: yes
      enable_gti: yes
      tags:
        - footag

  - name: Delete a NGFW Cluster
    l3fw_cluster:
      name: mycluster
      state: absent
      