- name: creating and deleting layer 3 firewalls
  connection: local
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create new firewall
    l3fw_cluster:
      smc_logging:
        level: 10
        path: /Users/davidlepage/Downloads/ansible-smc.log
      name: newcluster
      cvi_mode: standby
      primary_mgt: 0
      interfaces:
        - interface_id: 0
          cluster_virtual: 1.1.1.1
          network_value: 1.1.1.0/24
          macaddress: 02:02:02:02:02:02
          nodes:
            - address: 1.1.1.2
              network_value: 1.1.1.0/24
              nodeid: 1
            - address: 1.1.1.3
              network_value: 1.1.1.0/24
              nodeid: 2
            - address: 1.1.1.4
              network_value: 1.1.1.0/24
              nodeid: 3
        - interface_id: 1
          cluster_virtual: 2.2.2.1
          network_value: 2.2.2.0/24
          macaddress: 02:02:02:02:02:04
          nodes:
            - address: 2.2.2.2
              network_value: 2.2.2.0/24
              nodeid: 1
            - address: 2.2.2.3
              network_value: 2.2.2.0/24
              nodeid: 2
            - address: 2.2.2.4
              network_value: 2.2.2.0/24
              nodeid: 3
        - interface_id: 2
          nodes:
            - address: 3.3.3.2
              network_value: 3.3.3.0/24
              nodeid: 1
            - address: 3.3.3.3
              network_value: 3.3.3.0/24
              nodeid: 2
            - address: 3.3.3.4
              network_value: 3.3.3.0/24
              nodeid: 3
          vlan_id: 3
        - interface_id: 2
          nodes:
            - address: 4.4.4.2
              network_value: 4.4.4.0/24
              nodeid: 1
            - address: 4.4.4.3
              network_value: 4.4.4.0/24
              nodeid: 2
            - address: 4.4.4.4
              network_value: 4.4.4.0/24
              nodeid: 3
          vlan_id: 4
        - interface_id: 3
      tags:
        - footag

  #- name: Delete a NGFW Cluster
  #  l3fw_cluster:
  #    name: mycluster
  #    state: absent
      