- name: creating and deleting layer 3 firewalls
  connection: local
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create a layer 3 FW cluster with 3 members
    l3fw_cluster:
      smc_logging:
        level: 10
        path: /Users/davidlepage/Downloads/ansible-smc.log
      name: mycluster
      cluster_mode: standby
      mgmt_interface: 0
      interfaces:
        - cluster_nic: 0
          cluster_virtual: 1.1.1.1
          cluster_mask: 1.1.1.0/24
          macaddress: 02:02:02:02:02:02
          zone_ref: management
          nodes:
            - address: 1.1.1.2
              network_value: 1.1.1.0/24
              nodeid: 1
            - address: 1.1.1.3
              network_value: 1.1.1.0/24
              nodeid: 2
        - cluster_nic: 1
          cluster_virtual: 2.2.2.1
          cluster_mask: 2.2.2.0/24
          macaddress: 02:02:02:02:02:03
          nodes:
            - address: 2.2.2.2
              network_value: 2.2.2.0/24
              nodeid: 1
            - address: 2.2.2.3
              network_value: 2.2.2.0/24
              nodeid: 2
        - cluster_nic: 2
          nodes:
            - address: 3.3.3.1
              network_value: 3.3.3.0/24
              nodeid: 1
            - address: 3.3.3.2
              network_value: 3.3.3.0/24
              nodeid: 2
      default_nat: yes
      domain_server_address:
          - 10.0.0.1
          - 10.0.0.3
      enable_antivirus: yes
      enable_gti: yes
      tags:
        - footag

  #- name: Delete a NGFW Cluster
  #  l3fw_cluster:
  #    name: mycluster
  #    state: absent
      