- name: Facts about Layer 3 Firewall Policies
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Find all Layer 3 FW Policies
    l3fw_policy_facts:
  
  - name: Find details of a specific FW Policy
    l3fw_policy_facts:
      filter: fwpolicy

  - name: dump test output
    debug:
      msg: '{{ policies[0] }}'
  
  - fail: msg="Policy was invalid"
    when:
      - policies[0].name != "fwpolicy"