- name: Create a network element
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Example network element creation
    network_element:
      elements:
        - host: 
            name: myhost
            address: 1.1.1.1
            ipv6_address: 2001:0db8:85a3:0000:0000:8a2e:0370:7334
            secondary:
              - 1.1.1.2
              - 1.1.1.3
        - network:
            name: mynetwork
            ipv4_network: 1.1.1.0/24
            comment: created by dlepage
        - address_range:
            name: myrange
            ip_range: 1.1.1.1-1.1.1.10
        - interface_zone:
            name: myzone
        - domain_name:
            name: google.com
        - router:
            name: myrouter
            address: 172.18.1.254
            secondary:
              - 172.18.1.253
            ipv6_address: 2003:dead:beef:4dad:23:46:bb:101
        - ip_list: 
            name: mylist2
            iplist:
              - 1.1.1.1
              - 1.1.1.2
              - 1.1.1.3
              - 1.1.1.4
        - group: 
            name: group_referencing_existing_elements
            members:
              - host: 
                  name: grace
        - group:
            name: group_and_create_elements
            members:
              - host:
                  name: newhost
                  address: 1.1.1.1
        

              
        

