- name: Create a network element
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Example network element creation
    register: result
    network_element:
      smc_logging:
        level: 10
        path: /Users/davidlepage/Downloads/ansible-smc.log
      elements:
        - host: 
            name: hostb
            address: 1.1.1.1
            ipv6_address: 2001:0db8:85a3:0000:0000:8a2e:0370:7334
            secondary:
              - 1.1.1.2
              - 1.1.1.3
        - network:
            name: networka
            ipv4_network: 3.3.3.0/24
            ipv6_network: fc00::/7
            comment: created by dlepage
        - address_range:
            name: myrange
            ip_range: 1.1.1.1-1.1.1.10
        - interface_zone:
            name: myzone
        - domain_name:
            name: mydomain.com
            comment: foo
        - router:
            name: myrouter
            address: 172.18.1.254
            secondary:
              - 172.18.1.253
            ipv6_address: 2003:dead:beef:4dad:23:46:bb:101
        - ip_list: 
            name: myiplist
            comment: testlist
            iplist:
              - 1.1.1.1
              - 1.1.1.2
              - 1.1.1.3
              - 1.1.1.4
        - group:
            name: foogroup
            #remove_members: true
            #append_lists: true
            members:
                host:
                - hosta
                - hostb
                network:
                - networka
        - group:
            name: emptyregulargrp
            members:
        - router:
            name: myrouter2
            address: 13.13.13.13
        - network:
            name: mynetwork2
            ipv4_network: 13.13.13.0/24
        - netlink:
            name: mynetlink2
            gateway:
                name: myrouter2
                type: router
            network:
            -   mynetwork2
            domain_server_address:
                -   8.8.8.8
                -   8.8.7.7
            probe_address:
                -   10.10.10.1
            comment: added by ansible
    #     - host:
    #         - hosta
    #         - hostb
    #         - 2.2.2.4
    #   state: absent