- name: Facts about OSPF elements
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Find all OSPF v2 areas
    ospf_element_facts:
      element: ospfv2_area

  - name: Find a specific OSPF area with details
    ospf_element_facts:
      element: ospfv2_area
      filter: myarea
  
  - name: Find an OSPF profile containing name 'Default'
    ospf_element_facts:
      element: ospfv2_profile
      filter: Default

  - name: Get details for OSPF profile 'myprofile' and save as yaml
    register: results
    ospf_element_facts:
      smc_logging:
        level: 10
        path: ansible-smc.log
      element: ospfv2_area
      filter: myarea
      exact_match: false
      as_yaml: true

  - name: Write the yaml using a jinja template
    template: src=templates/facts_yaml.j2 dest=./ospf_element.yml
    vars:
      playbook: ospf_element