- name: Policy Based VPN operations
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create a new policy VPN with specified gateways
    policy_vpn:
      name: mynewvpn
      central_gw:
        - name: myfw
          type: internal_gateway
      satellite_gw:
        - name: extgw3
          type: external_gateway
          preshared_key: abc123
      gateway_tunnel:
        - tunnel_side_a: extgw3
          tunnel_side_b: myfirewall
          enabled: yes
          preshared_key: mynewkey
      tags:
        - footag