- name: Create a new BGP configuration
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Refresh policy
    policy_push:
      name: myfw3
      policy: TestPolicy
      wait_for_finish: yes
      max_tries: 10
      sleep: 3