- name: Create or modify an existing Policy VPN
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create or add gateways to a policy VPN
    policy_vpn:
      name: mynewvpn
      central_gw:
        - name: fw33
          type: internal_gateway
      satellite_gw:
        - name: anothergw
          type: external_gateway
          preshared_key: abc123
      gateway_tunnel:
        - tunnel_side_a: anothergw
          tunnel_side_b: fw33 - Primary
          enabled: yes
      tags:
        - footag