- name: 
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Task output
    register: result
    route_map:
      smc_logging:
        level: 10
        path: ansible-smc.log
      comment: mycomment
      name: newroutemap
      rules:
      -   action: permit
          comment: null
          match_condition:
          -   element: ip_prefix_list
              name: myprefixlist
              type: access_list
          name: with prefix
