- name: Obtain facts about Route VPNs
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Retrieve all Route VPNs
    route_vpn_facts:
      limit: 50

  - name: Retrieve a specific VPN
    route_vpn_facts:
      filter: rbvpn

  - name: Retrieve a specific VPN and expand special members
    route_vpn_facts:
      smc_logging:
        level: 10
        path: ansible-smc.log
      filter: myrbvpn
      expand:
        - rbvpn_tunnel_side_a
        - rbvpn_tunnel_side_b
        - vpn_profile_ref
        - monitoring_group_ref

  - name: Retrieve a specific route VPN and format as playbook YAML
    register: results
    route_vpn_facts:
      smc_logging:
        level: 10
        path: ansible-smc.log
      filter: myrbvpn
      as_yaml: true

  - name: Write the yaml using a jinja template
    template: src=templates/facts_yaml.j2 dest=./route_vpn.yml
    vars:
      playbook: route_vpn
      