- name: Create a rule
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Example rule creation
    firewall_rule:
      name: myrule
      policy: fwpolicy
      #sub_policy: my_sub_policy
      jump_policy: policy_to_jump_to (only required if action=jump)
      vpn_policy: vpn_to_use (only required if action=use_vpn)
      source:
        - host: foo
          address: 1.1.1.1
          filter_key: address
        - network: foonetwork
          ipv4_network: 2.2.2.0/24
          comment: foo
        - network: anothernet
          ipv4_network: 12.12.12.0/24
        - address_range: myrange
          ip_range: 3.3.3.1-3.3.3.5
        - router: myrouter
          address: 172.18.1.254
        - alias: $ EXTERNAL_NET
        - domain_name: domain2222.com
        - interface_zone: internal
        - group: 
            - foogroup
        - ip_list: mylist
        - country:
            - Armenia
            - United States
            - China
        - engine:
            - fw2
      destination:
        - network: any
      action: allow
      service:
        - service: any
      service:
        - tcp_service: 
            - HTTP
            - HTTPS
        - udp_service: DNS (UDP)
        - service_group: mysvcgrp
      logging:
        log_level: stored
        connection_closing: on
        log_accounting: on
        application_logging: on
        user_logging: on
      inspection_options:
        deep_inspection: on
        file_filtering: default
      connection_options:
        connection_tracking: normal
        idle_timeout: 20
        synchronize: on
        enforce_tcp_mss:
            min: 1400
            max: 1450
      blacklist_target: engine_to_apply_bl (only required if action=apply_blacklist)
      position: 1

  