- name: Create a service element
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Example service element creation
    register: result
    service_element:
      smc_logging:
        level: 10
        path: ansible-smc.log
      elements:
        - tcp_service: 
            name: myservice
            min_dst_port: 8080
            max_dst_port: 8100
        - tcp_service:
            name: newservice80
            min_dst_port: 80
        - udp_service:
            name: myudp
            min_dst_port: 8090
            max_dst_port: 8091
            comment: created by dlepage
        - udp_service:
            name: udp2000
            min_dst_port: 2000
        - ip_service:
            name: new service
            protocol_number: 8
            comment: custom EGP service
        - ethernet_service:
            name: 8021q frame
            frame_type: eth2
            value1: "0x8100"
        - icmp_service:
            name: custom icmp
            icmp_type: 3
            icmp_code: 7
            comment: custom icmp services
        - icmp_ipv6_service:
            name: my v6 icmp
            icmp_type: 139
            comment: Neighbor Advertisement Message
        - tcp_service_group:
            name: mygroup
            members:
                tcp_service:
                - newservice80
        - service_group:
            name: mysvcgrp
            members:
                tcp_service:
                - newservice80
                udp_service:
                - myudp
                - udp2000
                icmp_service:
                - custom icmp
        - udp_service_group:
            name: myudpservices
            members:
                udp_service:
                - myudp
                - udp2000
        - icmp_service_group:
            name: myicmp
            members:
                icmp_service:
                - custom icmp
        - icmp_service_group:
            name: myemptygroup
            members:
        - ip_service_group:
            name: myipservices
            members:
                ip_service:
                - new service

  - name: Delete all service elements
    register: result
    service_element:
        smc_logging:
            level: 10
            path: /Users/davidlepage/Downloads/ansible-smc.log
        state: absent
        elements:
            - tcp_service_group:
                - mygroup
            - udp_service_group:
                - myudpservices
            - service_group:
                - mysvcgrp
            - icmp_service_group:
                - myicmp
            - ip_service_group:
                - myipservices
            - tcp_service: 
                - myservice
            - udp_service:
                - myudp
            - ip_service:
                - new service
            - ethernet_service:
                - 8021q frame
            - icmp_service:
                - custom icmp
            - icmp_ipv6_service:
                - my v6 icmp
  - assert:
      that:
        - item.action == "deleted"
    with_items: '{{ result.state }}'

    