- name: Verifying NETCONF
  hosts: smc
  connection: smc_client
  vars:
    remote_user: FOOOOOOOOBAR
  gather_facts: no
  tasks: 
    - name: Verifying NETCONF
      tmp_mod:
        name: foobar
    - name: Verifying NETCONF
      tmp_mod:
        name: ttststesffs

